### ISSUE TITLE
量子ビットの2次元入力に対応

### ISSUE THREAD

**Issue by ShoyaYasuda** [tytansdk/tytan#28]
q[0][0]のような
内部的には1次元に伸ばして探索してOK。返すときに2次元に戻す

でも
q_0_0
のように記号化して渡すのでは？

**Comment by 34ro** [comment]
samplerの返した結果を2次元で表示したいというのが元々の動機になっているという仮定でのコメントです。

sympyは標準で2次元の変数に対応していないようですね。
またQUBOに変換する式はsympy, numpy, pandasのそれぞれの形式をサポートしているので、式を定義する段階で2次元の状態にしたいならそれぞれのライブラリを考慮する必要があります。
これらの外部ライブラリとは疎結合なほうが将来の保守コストの面で望ましいと思うので、Samplerの`run`を実行する段階までは素直に1次元の変数として扱い、最後に表示する部分だけ2次元で表示するutility的なメソッドを作るというのはどうでしょう？

```
result = [[{'q_0_0': 1.0, 'q_0_1': 0.0, 'q_0_2': 0.0}, -10, 2], [{'q_1_0': 1.0, 'q_0_1': 1.0, 'q_0_2': 0.0}, -5, 1]]
```
のような`result`が与えられたとして
```
print_as_table(result, "q_%d_%d", [0, 1, 2], [0, 1])
```
を実行したら
```
    0 1 2 energy count
--------------------
0 | 1 0 0 -10 2
1 | 1 1 0 -5 1
```
を返すイメージです。内部では[%演算子](https://docs.python.org/ja/3/library/stdtypes.html#printf-style-string-formatting)を第3,4引数でループして表にするだけ。

**Comment by ShoyaYasuda** [comment]
感謝いたします。有り難く採用させていただきAuto_arrayクラスを追加してみました。

>Samplerのrunを実行する段階までは素直に1次元の変数として扱い
賛成of賛成です。

添字は自動検出できそうだったので"q_{}_{}"で指定にしてみました。
おっしゃるとおり自然数ソートの件も解消できました！
