### ISSUE TITLE
tytanにおける整数の2進数表現の扱いに関して

### ISSUE THREAD

**Issue by ymski** [tytansdk/tytan#42]
quboで整数を扱う問題を解くことを考えています。
quboでは整数をそのまま扱うことができないため、2進数表現することによって定式化を行いました。
しかし、2進数表現で等式制約を解く場合は望ましくない結果を得ることがあります。
大変恐縮ですが、2進数表現による解法に関してアドバイスを頂くことは可能でしょうか？

以下にサンプルコードを添付しましたのでご確認頂けると幸いです。

```
from tytan import sampler, Compile, symbols

N = 3    # 正数を2進数表記する際のビット数
TARGET = 4    # 等号の右辺

expr = sum([symbols(f'q_{i}')*2**i for i in range(N)])     # Nビット列が表現する式
print(expr)    # q_0 + 2*q_1 + 4*q_2

h = (expr-TARGET)**2

qubo, offset = Compile(h).get_qubo()
solver = sampler.SASampler()
result = solver.run(qubo, shots=500)
print(result)    # [[{'q_0': 0, 'q_1': 0, 'q_2': 1}, -16.0, 379], [{'q_0': 1, 'q_1': 1, 'q_2': 0}, -15.0, 121]]
```

**Comment by ShoyaYasuda** [comment]
お返事が遅くなり大変失礼いたしました。
頂いたコードから、

[{'q_0': 0, 'q_1': 0, 'q_2': 1}, -16.0, 379]
[{'q_0': 1, 'q_1': 1, 'q_2': 0}, -15.0, 121]

コメント通りの2解が得られることを確認しました。エネルギー値から1番目の解がベストと判断されます。

ここまで問題ないようにお見受けしますが、望ましくない結果がどのような状態を指しているかお教えいただけますと幸いです。ご不明点もお気軽にコメントください。よろしくお願いいたします。

**Comment by ymski** [comment]
@ShoyaYasuda 
回答ありがとうございます。

> エネルギー値から1番目の解がベストと判断されます。
最も良い解自体はおっしゃる通り一番目の解であると認識しています。
結果の中に最適解を含んでいるという意味でこの結果は正しい結果を返しています。

一方で、最適解でない状態が121回観測されています。
さらに問題が複雑になるにつれ、最適解の出現する割合は小さくなっていくように見えました。
例として提示した簡単な小規模の問題においては、解が一意 又は 十分な精度で最適解に収束すること を期待していましたが、20%以上が最適解以外の結果を返しています。
この挙動により大規模な問題を解く際に、局所解につかまりやすくなるなどの問題は発生しますか？
またアニーリングで解く以上は、並列数に対して最適解がある程度の割合を占めることは期待できないのでしょうか？

**Comment by ShoyaYasuda** [comment]
@ymski 
おっしゃるとおり、
・最適解ではない解が20%以上も観測される
・問題が複雑になるにつれ、最適解の出現する割合は小さくなる
これらは疑似アニーリングのアルゴリズムの性質上、正常な現象です。（理想条件のアニーリングマシンでは1回で大域解が求まるはずですが、実際にはノイズの影響で同様の課題が発生していると思います）

>この挙動により大規模な問題を解く際に、局所解につかまりやすくなるなどの問題は発生しますか？
まさにそのようになります。複雑な問題ではshots=100（デフォルト）から500や5000に増やして大域解に1つでもヒットしてくれることを祈る形になります。

これを改善するにはアニーリングをよりゆっくり行う（内部の温度パラメータをゆっくり下げる）ことが考えられます。T_num=2000（デフォルト）というパラメータが入っていますので、これを大きくするとゆっくり丁寧にアニーリングすることになります。

result = solver.run(qubo, shots=100, T_num=2000)

（ちなみに、GASampler()という遺伝的アルゴリズムを使用したサンプラーも組み込まれていますが、本質的には同じ問題を抱えています。問題によってはSASampler()よりも精度が高い可能性はあります。）

>アニーリングで解く以上は、最適解がある程度の割合を占めることは期待できないのでしょうか？
私が知る限り、疑似アニーリングに共通の問題と考えています。

最適解のエネルギーが不明な場合（≒多くのコスト付の問題）
→そもそも解が最適解であるかどうか確認・保証できないため「最適解がN%以上になることを保証する」といったこともできません。
最適解のエネルギーが既知の場合（≒制約条件のみの問題）
→エネルギーから最適解であることが確認できるため「最適解がN%以上になることを保証する」の実装は可能です。（実用上は1個見つかれば十分ですので1個見つかったら終了、で良いとは思いますが）

お答えになっていますでしょうか。。よろしくお願いいたします。

**Comment by ymski** [comment]
@ShoyaYasuda 
丁寧なご回答ありがとうございます。

> 複雑な問題ではshots=100（デフォルト）から500や5000に増やして大域解に1つでもヒットしてくれることを祈る形になります。

やはり**1つでもヒットすることを祈る**という部分が重要なのですね。
問題が複雑や大規模になるとshotsを増やすことも難しい認識なのでバランスをとるのが難しそうです。
この質問をしたのは別の疑似量子sdkを用いた場合に解が一意に定まっているように見えたのが理由だったのですが、今思うと解をフィルタして最も良い解のみを出力していたのかもしれません。

大変よくわかりました。
こちらのissueは閉じさせていただきます。

**Comment by ShoyaYasuda** [comment]
@ymski 
大変有意義な議論に感謝いたします。
参考までに、別の疑似量子sdkを教えていただけましたら、私の興味として触ってみたいと思います。おっしゃるように解をフィルタしているか、もしくは性能が良すぎて小規模問題では1種類しかヒットしていないのかもしれません。。

**Comment by ymski** [comment]
@ShoyaYasuda 
こちらこそ大変有意義な議論に感謝いたします。

> 別の疑似量子sdkを教えていただけましたら
fixstars amplifyを使用した際に上で言及した現象に発生しました。

**Comment by ShoyaYasuda** [comment]
Fixstars amplifyですね、ありがとうございますm(_ _)m
