### ISSUE TITLE
Version0.0.5～0.0.19までのtagが0.0.20のコミットに紐づけられている

### ISSUE THREAD

**Issue by kamadocat** [tytansdk/tytan#45]
（意図的に同じにコミットに紐づけている場合はCloseしてください🙇）

https://github.com/tytansdk/tytan/releases にて用いられている0.0.5から0.0.19までのtagが全てhttps://github.com/tytansdk/tytan/commit/1feda1457417d5cb13a2737cf3f95b0f89b8b4df に紐づけられているような気がします。

おそらく、それぞれのバージョンは以下のコミットと対応しているのではないでしょうか。

- `0.0.5`: https://github.com/tytansdk/tytan/commit/53db5eefaf8efee6e4cdf90e098db2e61f3dc3fe
- `0.0.6`: https://github.com/tytansdk/tytan/commit/ac4bde75fdce367735786cd40bdbd545661198f5
- `0.0.7`: https://github.com/tytansdk/tytan/commit/e56f37f78515fc64ddd75daf9f0dfa93ed2fe028
- `0.0.8`: https://github.com/tytansdk/tytan/commit/5d81e9c3d96b26b0608fc873bd21a88201e6ca80
- `0.0.9`: https://github.com/tytansdk/tytan/commit/9d7fd4e900d44500ee46fd2828ce532ce8c70a8
- `0.0.12`: https://github.com/tytansdk/tytan/commit/8b4a6f43796335c124fe72c7b430cf5505031534
- `0.0.15`: https://github.com/tytansdk/tytan/commit/23d79dba1186c0fc77a49830c884be04106e53d7
- `0.0.17`: https://github.com/tytansdk/tytan/commit/e1a007ed747bfde1e2f86dcd6c2928511269770f
- `0.0.18`: https://github.com/tytansdk/tytan/commit/bcdddf3642f804903cb21e6f6f9465745920ab68
- `0.0.19`: https://github.com/tytansdk/tytan/commit/145ee8386606d06915532f1878f4dc8bf6d76d2c

非常に細かい話となってしまって申し訳ありません。

**Comment by ShoyaYasuda** [comment]
確認が遅くなりました！タグとSHA番号の紐づけが間違っていたようで、ブラウザ上では修正できないらしいのでChatGPTに聞きながらgitコマンドでなんとか修正できました！ありがとうございます😊（git初心者なのでご指導ありがたいです！）
